apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-pvc
  namespace: jie
  labels:
    app: ssd
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G