apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-pvc
  namespace: jie
  labels:
    app: mysql
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
