apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mysql
  namespace: jie
  labels:
    app: mysql
spec:
  serviceName: wordpress-mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        tier: db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 120m
            memory: 1024Mi
          requests:
            cpu: 60m
            memory: 500Mi
        envFrom:
          - configMapRef:
              name: mysql-conf
          - secretRef:
              name: mysql-secret

        volumeMounts:
        - name: mysql-volume-pvc
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-volume-pvc
        persistentVolumeClaim:
          claimName: mysql-volume-pvc